### ISSUE TITLE
Разработка пользовательского интерфейса

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#1]
- [x] Профиль игрока
- [x] Выбор/ввод ответа на диалоговые сообщения

**Comment by elevir** [comment]
fixed with Build ver 1.0.6190.33081

**Comment by ElenaKulikova** [comment]
В версии 1.0.6219.28279 в начале игры не на всех кнопках есть их название, а на тех что есть наплывают друг на друга

**Comment by elevir** [comment]
Исправллено в сборке  ver 1.0.6219.33948

**Comment by ElenaKulikova** [comment]
В версии 1.0.6219.33948 в начале игры не на всех кнопках есть их название

**Comment by ElenaKulikova** [comment]
Поправка: после регистрации надпись появляется.

**Comment by ElenaKulikova** [comment]
Так задумано?
