### ISSUE TITLE
Разработка серверной части

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#2]
- [x] Обмен данными между пользователями
- [x] Рейтинг

**Comment by ildan95** [comment]
Что означает "диалог с пользователем"?

**Comment by Lobachevskiy** [comment]
Обновил более понятной формулировкой.

**Comment by elevir** [comment]
fixed with Build ver 1.0.6190.33081

**Comment by ElenaKulikova** [comment]
В версии 1.0.6219.28279 если подключаешься в последний момент, то игра зависает

**Comment by elevir** [comment]
Исправллено в сборке  ver 1.0.6219.33948
