### ISSUE TITLE
Разработка игры «Runner»

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#3]
- [x] Передвижение по полю
- [x] Локация
- [x] Бонусы (внешний вид, действие и пр.)
- [x] Получение/трата бонусов и «денег»
- [x] Прокачка персонажа
- [x] Бот

**Comment by elevir** [comment]
fixed with Build ver 1.0.6190.33081

**Comment by ElenaKulikova** [comment]
В версии 1.0.6219.28279 ошибка, если мой игрок добегает последним, то не высвечивается табло результатов.

**Comment by elevir** [comment]
Исправллено в сборке  ver 1.0.6219.33948

**Comment by ElenaKulikova** [comment]
В верссии 1.0.6220.28303 ошибка, при покупке бонусов в магазине они не отображаются в состоянии игрока
