### ISSUE TITLE
Передвижение по полю

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#6]
Необходимо реализовать движение игроков в игровом пространстве.

Относится к https://github.com/V3416TheRealRTZ/game-collection/issues/3

**Comment by ElenaKulikova** [comment]
Результат тестирования в версии 1.0.6190.33081:
1. Проблемы с прыжком (прыгает через раз)

**Comment by elevir** [comment]
Исправлено в build ver 1.0.6196.30078

**Comment by ElenaKulikova** [comment]
Результат тестирования в версии 1.0.6196.30078:

Проблемы с прыжком (прыгает через раз)

**Comment by elevir** [comment]
Не получается исправить, особенности движка.
