### ISSUE TITLE
Бонусы

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#8]
В игровом пространстве находятся различные бонусы, которые могут быть подобраны игроками. Необходимо реализовать данный механизм, включая подбираемые объекты и их эффекты.

Относится к https://github.com/V3416TheRealRTZ/game-collection/issues/3

**Comment by ElenaKulikova** [comment]
Результат тестирования в версии 1.0.6190.33081:
1.Невозможно собрать первый бонус "Х2" (возможно из-за проблемы с прыжком)

**Comment by elevir** [comment]
Первый бонус собрать реально
