### ISSUE TITLE
Получение/трата бонусов и «денег»

### ISSUE THREAD

**Issue by Lobachevskiy** [V3416TheRealRTZ/game-collection#9]
Реализовать механизмы использования денег для покупки различных внутриигровых способностей.

Относится к https://github.com/V3416TheRealRTZ/game-collection/issues/3

**Comment by elevir** [comment]
fixed with Build ver 1.0.6190.33081

**Comment by ElenaKulikova** [comment]
Результат тестирования в версии 1.0.6196.30078:

1. Бонусы подбираются, а потом пропадают (в начале игры было подобрано 5 камней и они отображались в верхнем левом углу, а потом пропали, или так и должно быть?)

**Comment by elevir** [comment]
Даются на время
